pipeline {
    agent any

    tools {
        gradle 'gradle'
    }

    stages {

        stage('github clone') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/back']],
                    userRemoteConfigs: [[credentialsId: 'git-token', url: 'https://github.com/Seunginlee00/SimpleProjects.git']]
                )
                sh 'cd backend && git log -1'
            }
        }

        stage('Remove') {
            steps {
                dir('backend/build/libs') {
                    sh 'rm -f *.jar || true'
                }
            }
        }

        stage('source build') {
            steps {
                echo "${env.BUILD_ID}"
                dir('backend'){
                    sh 'chmod +x ./gradlew'
                    sh './gradlew clean bootJar'
                }
            }
        }

    stage('Rename JAR') {
        steps {
            dir('backend/build/libs') {
                sh '''
                    echo "[현재 JAR 파일 목록]"
                    ls -lh

                    jar_file=$(ls *.jar | head -n 1)
                    echo "[Rename 시도: $jar_file → app.jar]"

                    if [ "$jar_file" != "app.jar" ]; then
                      mv "$jar_file" app.jar
                    else
                      echo "이미 app.jar 입니다. rename 생략"
                    fi

                    echo "[결과]"
                    ls -lh
                '''
            }
        }
    }

      stage('Check JAR built') {
          steps {
              dir('backend/build/libs') {
                  sh '''
                      echo "[현재 디렉토리]"
                      pwd

                      echo "[현재 파일 목록]"
                      ls -alh

                      echo "[파일 타입 검사]"
                      file app.jar || echo "app.jar not found!"
                  '''
              }
          }
      }

    stage('Deploy') {
        steps {
            sshagent (credentials: ['host-ssh']) {
                // app.jar를 SSH 대상 서버로 직접 복사
                sh '''
                    echo "[Deploy: app.jar 파일 서버로 전송 중]"
                    scp -o StrictHostKeyChecking=no backend/build/libs/app.jar ubuntu@172.17.0.1:/home/ubuntu/docker/app.jar

                    echo "[원격 서버에서 배포 스크립트 실행]"
                    ssh -o StrictHostKeyChecking=no ubuntu@172.17.0.1 "/home/ubuntu/docker/deploy_backend.sh"
                '''
            }
          }
        }
    } //stages
} // pipeline
