# 1단계: 빌드
FROM gradle:8.13-jdk17 AS build

WORKDIR /app

COPY backend/gradle /app/backend/gradle
COPY backend/gradlew /app/backend/gradlew
RUN chmod +x /app/backend/gradlew

COPY backend/build.gradle /app/backend/
COPY backend/settings.gradle /app/backend/
COPY backend/src /app/backend/src

WORKDIR /app/backend

RUN ./gradlew bootJar --no-daemon

# 2단계: 실행
FROM eclipse-temurin:17-jdk

WORKDIR /app
COPY --from=build /app/backend/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
